### ISSUE TITLE
Cannot install pip packages - permision denied

### ISSUE THREAD

**Issue by asmith26** [geodocker/geodocker-jupyter-geopyspark#96]
Hi there

I'm using the docker image **quay.io/geodocker/jupyter-geopyspark:blog** (also contains the fantastic geonotebook), and I'm trying to install with `!pip install geopandas`. Unfortunately I'm getting an error:

```
PermissionError: [Errno 13] Permission denied: '/usr/lib/python3.4/site-packages/descartes-1.1.0.dist-info'
```

Attempting to sudo gives `/usr/bin/sh: sudo: command not found`

Is there anyway I can install additional pip packages (preferably through a notebook so I get the correct python environment)?

Many thanks for these fantastic docker containers!

**Comment by jamesmcclain** [comment]
If the container is running and you type `docker ps -a`, you should see something like the following
```bash
...
25a9c0ebf3ef        quay.io/geodocker/jupyter-geopyspark:blog   "/scripts/jupyterhub…"   About a minute ago   Up About a minute   8000/tcp            sharp_kapitsa
...
```
which gives you the name and id of the running container. 

Given that information, you can shell into the container by typing something like `docker exec -it -u root 25a9c0ebf3ef bash`.

You can then type `pip3 install geopandas` to attempt to install the package as root.  This *will not* work, though, because gcc is not installed in the container.  You may be able to make some progress by installing gcc (using `yum`) from within the root shell.  I am afraid that I do not know how easy or difficult that will be.

(I have confirmed that pip3 installing packages from the shell does make them available in notebooks.)

**Comment by asmith26** [comment]
Thanks very much for your help @jamesmcclain!

For reference, my steps to install geopandas for use with the notebooks:
```
$ docker exec -it -u root 25a9c0ebf3ef bash
[root@25a9c0ebf3ef tmp]# yum install gcc python34-devel.x86_64 gcc-c++ 
[root@25a9c0ebf3ef tmp]# pip3 install geopandas
```

Perhaps we can add these to the [DockerFile](https://github.com/geodocker/geodocker-jupyter-geopyspark/blob/master/Dockerfile) (I can create a pull request if you like)? geopandas is quite a commonly used geospatial library for (small) vector data.

**Comment by lossyrob** [comment]
@asmith26  :+1: for adding geopandas to the Dockerfile. A PR would be appreciated!

**Comment by asmith26** [comment]
Done: https://github.com/geodocker/geodocker-jupyter-geopyspark/pull/97

Please feel free to amend to follow any standards that you follow - I am a bit confused because the [Dockerfile says to pull from itself at tag `base-7`](https://github.com/geodocker/geodocker-jupyter-geopyspark/blob/master/Dockerfile#L1) (and I don't see any other "yum install" within this Dockerfile, thus I was wondering if I should have put it into the base image it pulls from).
